export enum FormFieldType {
    INPUT = "input",
    FLOATINGLABELTEXTFIELD = "floatingLabelTextField",
    TEXTAREA = "textarea",
    SELECT = "select",
    MULTISELECT = "multiSelect",
    TEXT = "text",
    PHONE_INPUT = "phoneInput",
    DATE_PICKER = "datePicker",
    CHECKBOX = "checkbox",
    FILEUPLOAD = "fileUpload",
    RADIO = "radio",
    RADIOGROUP = "radioGroup",
    RICHTEXTEDITOR = "richTextEditor",
    OTP_INPUT = "otpInput",
}
